title = "Spitlo.com"
base_url = "https://spitlo.com"
taxonomies = [
  { name = "categories", feed = true },
  { name = "technologies", feed = true },
]

build_search_index = true
compile_sass = true
default_language = "en"
generate_feed = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "zenburn"
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[link_checker]
skip_anchor_prefixes = [
  "https://github.com",
]
