title = "Spitlo.com"
base_url = "https://spitlo.com"
author = "Spitlo"
taxonomies = [
  { name = "categories", feed = true },
  { name = "technologies", feed = true },
]

build_search_index = true
compile_sass = true
default_language = "en"
generate_feeds = true
minify_html = true

[link_checker]
skip_prefixes = [
  "https://vlang",
]
skip_anchor_prefixes = [
  "https://github.com",
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-gruvbox-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-gruvbox-light.css" },
]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[search]
include_title = true
include_description = true
include_content = true
include_date = true
