title = "Spitlo.com"
base_url = "https://spitlo.com"
author = "Spitlo"
taxonomies = [
  { name = "categories", feed = true },
  { name = "technologies", feed = true },
]

build_search_index = true
compile_sass = true
default_language = "en"
generate_feeds = true
minify_html = true

[link_checker]
skip_prefixes = [
  # "https://vlang",
  # "https://tic80",
  "http"
]
skip_anchor_prefixes = [
  "https://github.com",
]

[markdown]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[markdown.highlighting]
error_on_missing_language = true
light_theme = "gruvbox-light-medium"
dark_theme = "gruvbox-dark-medium"
style = "class"

[search]
include_title = true
include_description = true
include_content = true
include_date = true
