build_search_index = true
compile_sass = true
generate_feed = true
highlight_code = true
highlight_theme = "ayu-light"
minify_html = true

base_url = "https://spitlo.com"
taxonomies = [
  { name = "technologies", feed = true },
]
