name: Deploy
 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: spitlo/zola-deploy-action
        uses: spitlo/zola-deploy-action@master
        env:
          SITE_URL: "https://spitlo.com"
          TOKEN: ${{ secrets.TOKEN }}
